[package]
name = "docker-rust-hello"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
postgres = "0.19.3"
log = "0.4"
tokio = { version = "1", features = ["full"] }
tokio-postgres = "0.7"

