version: '2'

services:
  
  server:
    image: rust-app
    build:
      context: .
      target: final
    expose:
      - 6001
    ports:
      - 6001:6001
    networks:
      - mi_red_docker
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=tienda_db
      - POSTGRES_PASSWORD=1192141
      - POSTGRES_USER=benjamin
      - postgres_host_auth_method=trust
    expose:
      - 5432  
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mi_red_docker

networks:
  mi_red_docker:
    external: true
