version: '2'

services:
  
  server:
    image: rust-app
    build:
      context: .
      target: final
      args:
        - DATABASE_URL=postgres://benjamin:1192141@db:5432/tienda_db
    ports:
      - '8080:8080'
    networks:
      - mi_red_docker
    depends_on:
      - db

  db:
    image: postgres:latest
    networks:
      - mi_red_docker
    environment:
      - POSTGRES_DB=tienda_db
      - POSTGRES_PASSWORD=1192141
      - POSTGRES_USER=benjamin
      - postgres_host_auth_method=trust
    ports:
      - '5432:5432'
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./data:/var/lib/postgresql/data

volumes:
  data: {}  
  

networks:
  mi_red_docker:
    external: true